// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUAgBIvf0NYyAOYVWfzmaAJNdPb2xPxLc',
    appId: '1:246672128053:web:6d7642842ad975f7d3197c',
    messagingSenderId: '246672128053',
    projectId: 'ai-agent-app-d4ba4',
    authDomain: 'ai-agent-app-d4ba4.firebaseapp.com',
    storageBucket: 'ai-agent-app-d4ba4.firebasestorage.app',
    measurementId: 'G-J7PDCVYJY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2L5XQEsB9lbXiSN83kOn_X5578b7dGEo',
    appId: '1:246672128053:android:042b585d3a02d5c4d3197c',
    messagingSenderId: '246672128053',
    projectId: 'ai-agent-app-d4ba4',
    storageBucket: 'ai-agent-app-d4ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOzRTVRMmgQkL9givKTCR81s2X36L4v8',
    appId: '1:246672128053:ios:ca09752ad13b97b5d3197c',
    messagingSenderId: '246672128053',
    projectId: 'ai-agent-app-d4ba4',
    storageBucket: 'ai-agent-app-d4ba4.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOzRTVRMmgQkL9givKTCR81s2X36L4v8',
    appId: '1:246672128053:ios:ca09752ad13b97b5d3197c',
    messagingSenderId: '246672128053',
    projectId: 'ai-agent-app-d4ba4',
    storageBucket: 'ai-agent-app-d4ba4.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUAgBIvf0NYyAOYVWfzmaAJNdPb2xPxLc',
    appId: '1:246672128053:web:651fde29aa4ade81d3197c',
    messagingSenderId: '246672128053',
    projectId: 'ai-agent-app-d4ba4',
    authDomain: 'ai-agent-app-d4ba4.firebaseapp.com',
    storageBucket: 'ai-agent-app-d4ba4.firebasestorage.app',
    measurementId: 'G-6JTLS7KZ1Y',
  );

}